name: "Local Notify"
version: "1.0.3"
slug: "localnotify"
description: "Simple local HTTP notify endpoint"
arch:
  - aarch64
startup: services
boot: auto

build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:latest"

ports:
  8790/tcp: 8790

options: {}
schema: {}

hassio_api: true
homeassistant_api: true
