name: "Local Notify"
version: "1.0.3"
slug: "localnotify"
description: "Simple local HTTP notify endpoint"
url: "https://github.com/tomastt2/localnotify-addon"
arch:
  - aarch64
startup: application
boot: auto
host_network: true
options: {}
schema: {}
image: "local/{arch}-addon-localnotify"